<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Test Maven Suite" duration-ms="546" started-at="2018-11-10T05:43:45Z" finished-at="2018-11-10T05:43:46Z">
    <groups>
    </groups>
    <test name="Test Maven Testing" duration-ms="546" started-at="2018-11-10T05:43:45Z" finished-at="2018-11-10T05:43:46Z">
      <class name="com.qa.tests.DemoTest">
        <test-method status="PASS" signature="sub()[pri:0, instance:com.qa.tests.DemoTest@6bf256fa]" name="sub" duration-ms="6" started-at="2018-11-10T05:43:45Z" finished-at="2018-11-10T05:43:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method status="PASS" signature="sum()[pri:0, instance:com.qa.tests.DemoTest@6bf256fa]" name="sum" duration-ms="0" started-at="2018-11-10T05:43:45Z" finished-at="2018-11-10T05:43:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
      </class> <!-- com.qa.tests.DemoTest -->
      <class name="com.qa.tests.DemoTest1">
        <test-method status="FAIL" signature="excelDataValidate()[pri:0, instance:com.qa.tests.DemoTest1@6cd8737]" name="excelDataValidate" duration-ms="450" started-at="2018-11-10T05:43:45Z" finished-at="2018-11-10T05:43:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [user2] but found [user1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [user2] but found [user1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.tests.DemoTest1.excelDataValidate(DemoTest1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- excelDataValidate -->
        <test-method status="PASS" signature="sum1()[pri:0, instance:com.qa.tests.DemoTest1@6cd8737]" name="sum1" duration-ms="1" started-at="2018-11-10T05:43:46Z" finished-at="2018-11-10T05:43:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum1 -->
        <test-method status="PASS" signature="sub1()[pri:0, instance:com.qa.tests.DemoTest1@6cd8737]" name="sub1" duration-ms="0" started-at="2018-11-10T05:43:46Z" finished-at="2018-11-10T05:43:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub1 -->
      </class> <!-- com.qa.tests.DemoTest1 -->
    </test> <!-- Test Maven Testing -->
  </suite> <!-- Test Maven Suite -->
</testng-results>
